### PR TITLE
Death Knight: Add Raise Dead and Sacrificial Pact.

### PR DESCRIPTION
**Pull request by ultijlam**

### CODE REVIEW

**Comment by Hemario** [comment]
Should probably add a SpellRequire condition to check if we actually have a pet present for Sacrificial Pact

**Comment by ultijlam** [comment]
No, unfortunately the raised ghoul is not a pet. It just occurred to me that perhaps it counts as a totem, so I'll check that when the servers come back up today. I currently work around this by using the spell cooldown as a proxy for the lifetime of the ghoul since the ghoul dies one minute after it is summoned.

**Comment by Hemario** [comment]
Yes, but the Ghoul can be dismissed can't it? (for example when performing a skip it is advisable to dismiss your pet in order to not pull extras)

**Comment by ultijlam** [comment]
No, at least not for Blood or Frost. There's no unit frame for the ghoul. It's a minion, not a pet.

**Comment by ultijlam** [comment]
I actually just summon and sacrifice it right away right now in dungeons so that I don't have to manage the timer on it.

**Comment by Hemario** [comment]
> 
> 
> No, at least not for Blood or Frost. There's no unit frame for the ghoul. It's a minion, not a pet.

I guess I got confused. Blood DK still have Control Undead though right? The ability to permanently (well, 5 minutes) control an Undead. And this controlled pet is a pet. I remember using it on the stitchworks in Necrotic Wake when leveling a bit.

**Comment by Hemario** [comment]
Just checked myself, the Ghould raised by "Raise Dead" spell is in fact a totem. We'll have to add DK to the TOTEM_CLASS constant though because otherwise the module won't even initialize.

**Comment by ultijlam** [comment]
I have that in a local branch right now, but there are some other changes to Ovale that are needed to properly support DK ghouls. I'll just make an issue in the Ovale ticket tracker to explain the issue and changes that need to be made.  In the meantime, the method in this pullup is a workaround for the problem until Ovale is fixed.

**Pull request merged**
